##################################################################################
# RAUC system conf compatible with the community partition layout 
# and with the community writing to sdcard.
# To write to the eMMC, e.g. in FRDM-IMX93, use mmcblk0.
# TODO: if anyone cares, add a @@MMCDEVICE@@ literal and sed it like the MACHINE
#       I might do it after proving "backward compatibility" to the current meta-rauc-community project
##################################################################################
[system]
compatible=@@MACHINE@@
bootloader=uboot
data-directory=/data/

[keyring]
path=/etc/rauc/ca.cert.pem

# ----------------------------------------------------------------------
# SLOT A
# ----------------------------------------------------------------------
[slot.rootfs.0]
device=/dev/mmcblk1p5
type=ext4
bootname=A

[slot.boot.0]
device=/dev/mmcblk1p1
type=vfat
parent=rootfs.0

# ----------------------------------------------------------------------
# SLOT B
# ----------------------------------------------------------------------
[slot.rootfs.1]
device=/dev/mmcblk1p6
type=ext4
bootname=B

[slot.boot.1]
device=/dev/mmcblk1p2
type=vfat
parent=rootfs.1
