name: meta-rauc-qemux86 CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
    paths:
      - 'meta-rauc-qemux86/**'
  pull_request:
    branches:
      - master
    paths:
      - 'meta-rauc-qemux86/**'
jobs:
  build:
    name: meta-rauc-qemux86 Build
    runs-on: ubuntu-22.04
    steps:
      - name: Install required packages
        run: |
          sudo apt-get install diffstat chrpath
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone poky
        run: git clone -b master git://git.yoctoproject.org/poky
      - name: Clone meta-rauc
        run: git clone -b master https://github.com/rauc/meta-rauc.git
      - name: Initialize build directory
        run: |
          source poky/oe-init-build-env build
          bitbake-layers add-layer ../meta-rauc
          bitbake-layers add-layer ../meta-rauc-qemux86
          echo 'INHERIT += "rm_work"' >> conf/local.conf
          echo 'DISTRO_FEATURES:remove = "alsa bluetooth usbgadget usbhost wifi nfs zeroconf pci 3g nfc x11 opengl ptest wayland vulkan"' >> conf/local.conf
          echo 'SSTATE_MIRRORS = "file://.* http://195.201.147.117/sstate-cache/PATH"' >> conf/local.conf
          echo 'DISTRO_FEATURES:append = " rauc"' >> conf/local.conf
          echo 'IMAGE_INSTALL:append = " rauc"' >> conf/local.conf
          echo 'IMAGE_FSTYPES = "tar.bz2 wic"' >> conf/local.conf
          echo 'WKS_FILE = "qemux86-grub-efi.wks"' >> conf/local.conf
          echo 'EXTRA_IMAGEDEPENDS += "ovmf"' >> conf/local.conf
          echo 'PREFERRED_RPROVIDER_virtual-grub-bootconf = "rauc-qemu-grubconf"' >> conf/local.conf
      - name: bitbake parsing test
        run: |
          source poky/oe-init-build-env build
          bitbake -p
